# Generated by Django 4.2.5 on 2024-09-27 01:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to='images/', validators=[api.models.validate_image_or_svg]),
        ),
    ]
